env:
  global:
    - secure: hOcJjrGSUuUdbGal/EYPh/Tq4mjfqmIxgtbaZxKj0tKAHjgnRmhj0K4GdwUuYPberHkWNYPYaBFCWZa6g6jXtEvIwzPk85iVB/vuJQHHxuB8z+I6Ngb6ch61GFnhhMhSWuScrVGMQDguEGFPJJqkYUWOtPoKdJlTZkO/lMGs8CcS5tQNXEyShuDSojDRcNRU/jdXv9+AtsMoRJkEg40jvPhSGOlWj6+sBOkTl5Uk9i4OzNZah+c3FCkaXR3ppB0nHaMjtatoivg0PJ2HNMr8j0krHo/MsK4OaCoiv5iLuO8XPkt6s+le0BpA6nq6R47Gz2ZnDMjhTocw1y64rEPD2hB+Xie+a8koApQ9aBKiN25PI5KCH6WJbzXtkK6Y1aePVZwuCR2bRoCXO68WrYDJIdMHLtdYKbJOMpHogVgB6oIC/bMJHdL0BG2TxNopIS9dgRFtmoMzE1LkUKaDvYsBArej0iPTmOfuZ+XSWx+xKJvE4n+LNmtXpsD4PzWKoB6PEEnhp/S8vU4H9KOIcNgm3fvGp4O6pCu2kNIVIkYBCXIv3hM6QBS4P2GDvT2i16QzrQajXisYUxeHM8d/QxDRHhXuh/nreSGYSB0dQ3Qp9/IJXVBweeTDrfS3vPhVtMBCoyfUqELLhzZwblQC29nLUrjKhjHjK4npXulEKiUTLY8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/quidsup_notrack_trackers
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
