env:
  global:
    - secure: tDHbLgHBF70BRpf/TG/ZU3OPfRXWGNlqkgEN0UqKEPieAeKr593+Cr8+vDNOA5cspsqqDcaD9Xmdy5FLrzCkdGoos3OH2wQBxrui9Hh3+gAENg65jbKYa/69fMQJ2UbE6lNUQ81MKaReFz0S12sbwgBGoWWkzxE1123wdZEvQmolhJ3tKsDP3D0GN2IZRUQe71LBOP5hSg3+KayGwW+JoicDgLfxYeuC9URcai6NDDOSa1UuSEZCPAs6bpBSKm+EQs9rbLW/PZOAOYjHg5I/xokPAIKM0Iaw8TcZJxr3l0VjZai393jen26YL/PwVGJC1mLnip7YLMPATgOFKMAR9891HzXab/AWwDf9XPJlnISour8Q7y2TgxN8ZguvmGJpIfTete6dxOVjIJmdfyzTJ3hopL9cDlrQ34XU8kp6RVjtC3Y4eomEmqnbrcFuTSM2u2uJ6ozkn1rIwlnK/z+ksbvs0HDOx1xA8dRCmiAgtH/GX7Gt2i0oicH46vYFndCzHMSsl/qE2iQQ056Yv8gxcBbjKOXN2Qfs4E9E6Zy+4up9IO/NS3uCQaXMKkAX3fh9Wr9LDEeSv6jau+k7DZtf5LeuE0GElV4ySSFpb0C6OYND+mcDi50KEuhul5b2ok2G/uS4Y4MrMATkG7R27+Jud45IwJDyAEJZY5+PF4LLmPQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/quidsup_notrack_trackers
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
