env:
  global:
    - secure: j2ICg+uXiX7jlMUehftq95NsCOwZjjl1HEvZh84XoJ+1tSqCbEniqu2ruMB9UJUYwt+KGy8k3isoqza/NuMyJmsyDvOrgcpcoM8NnV28Ufv34jt0UlrDq8HkcthTco0Mreg/TwucvxunDJ1dIO8wE5htffEb2gmEpdwzf2/I9TO4Cx6Cg7hQBep+iy+m9YsBufbi+N8wmvvU0cfsk7Sam4TdfOuC8MFkovzv43ozGVaUh06NF+5GOt9A1k6PbZ6Ddo0U9Xd1mGmXrtygvrOToX+hS+sZcA8iyZJgJG+Hm5Lfbpq/hgBIRr2T3BpgJQK9Rryp/M4JdRL00DtWAWoSjqv0WwaI7rJ+Aa1C5YwPMgyvArjY30mpgD63hjGYyXKpYLD3hf5l1DZLe3PFLqlAyAy6pXlNFqCAN25YSMqOGXibIrDCpCuLVb2nMq4JsScb7RNMSUNYiUemiSLEKb2FG1jfIoMHMkl3TtICDmmPV/2QeYmklQ851fUhxFdxnKZooldkjIoittqURqT2QxMvJL2f8Hhyi1mQFT0/GzJFnuCOICeHNWzJf2KhKU0blTmy5d3A7gOmfibsiIERxCuPHG0q2dRVp9JqnRE8DAStYLERGxbF9ooRB4sDPHrdajNRaBlzcrluOngvP00yWvOGTVlntdtLxg7352l0N/oX++8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/quidsup_notrack_trackers
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
