env:
  global:
    - secure: vkXNezpWfsFVKruPQsIeU94rIM7p0ZOejXY1YWQmGJQLIHKqGoWaHO2haZ9jW8Hv35rSUvtAcAFz0YQoWdp7XKvlYAqnn2baftDitwUMDUbBJqj6yUogU2fS1tzifCG5dxnub4bzOXHveSoJVuNpvrscXFrUHJlnVgoHM4rRZDZLMMZ43a7B0A1nIWxost97cBzmCaWI9GGorjGmMFY8/a2Y/rzVlkNdjbdrwbPIn8hSSLlkrczJ7b2ATjHWEL7/RQkcfY30zMmIrRT4ruuJmVSrZmHwtJeQBLJrJMaJhf6ROldJI+5SPg4Tl27RsqFWaKqTYBuvLe1/tUyd3FuXzCTi47Sx66YUU6BueiCdaW9wI/LQoNVbPcDQmENObhItqkyWtzuv5pDRVX2lYRooi0vLWXLE1k8FZGLg6UQmuTOJEFxxrAqtwSClxWNcCCy3Y4BjIRVeSffhPZ4ZgOSDHrT8nu6DQNU67FhrpME70+eO16FM1Fk9soqKKAzs1rJBoNpuPLL235pbo9+PS2yIP2RL9wtR6cXUrDPjWPQKufpnMpCe6d+38ExMXDI8prowXAs+NZ38eABex7B+XwGUuj6/UrQWDEfxuhz/d/utkyLjpuB/zS+FVWMVI0J1qpZ7nXhnxTgovMjple9Dh6Hu5EKqg+RsTOZ2Y5+oiPE4XgM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/quidsup_notrack_trackers
    - GIT_BRANCH: master
    - WHITELISTING_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/dev-center/whitelisting/whitelisting.py
    - UPDATE_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/repository-structure/master/update.py
    - ADMINISTATION_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/repository-structure/master/administration.py

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests
  - wget "${WHITELISTING_LOCATION}" -o /dev/null -O whitelisting.py && chmod +x whitelisting.py
  - if [[ ! -f .admin ]]; then wget "${UPDATE_LOCATION}" -o /dev/null -O update.py && chmod +x update.py; else echo "No need to download/update update.py."; fi
  - if [[ ! -f .admin ]]; then wget "${ADMINISTATION_LOCATION}" -o /dev/null -O administration.py && chmod +x administration.py; else echo "No need to download/update administration.py."; fi

script:
  - python3 ./update.py

notifications:
  on_success: change
  on_failure: always
