env:
  global:
    - secure: nA61mkGX7uhza+DpSLnxzAdX1AE9OKRLXblKFAwMmqf2W7EuTHkja2iT5qBtLl+nUHT3y6ORkSWsc64KkM/NZqqiJVVoNzMcX61KEUq3hxB043ZE4KQ0OpyFzCQ/LO9eGgI/jW+kFI2gf5SbXHap3snBcOjQGREXs0Oq6TTbv+Dy1SD9ByjV+b39bT2DqJN0hR0eg4EcW+1VNgyKJH2+uH/2xsclgIwONzKf11S6BIjtO4M6HgJiAkwXmqj1H5IjKkHr9hm/o0Q8gXCou7OEymMAyUl2oLRjlyNjpSNM1SRATMBmw+VqL4NCJLjyU1tjpmBlMXDnQGZtPoysSrR5GR1GXZZkLUEQon5p8WlQAE8dxFGywqWuymCKhc5VmbfOjcG/kQRIQvRuZejWOmaUwVUsztRf4NN7tsz51iL4GnGFaZa+w0FfKJrD4vpRUSj8xK3LK96K6Ss+OGeNtZULIwiz5mxKP/HFEFc/8fJVhWJPNYraU6CrGa67kE6qIoT+OO31RZFEs64IySjz7h/1y6mxWw+ajZmUoHeEQ8qysU6NcPAASp+ulrlZEiu1OM8nPXDRNFKL0VOET3VTskeIMiOmDZs+RkTZKJbgu9f+cjzQCWnV+5xIuLrXOUyb48wBjwvtpcxly2jwo3x72rpeorbYAY99ECzl6QlfmyYwAvI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/quidsup_notrack_trackers
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
