env:
  global:
    - secure: ACc4Xko8IughbFqUYkXNJsjD3UmhGH6RbKRvDm9EEj5ZlYU3mo9KqV8cOhqXb44xPQiEL2g2iQguQRFrYIAYdc88K/AVoMLfzLQ1NMU1NphbM46n/v0X4ILOkfgEVZXmZPkCylGfoXRHkvlYr7X1zi3qOkrInW9ARnIx1HvhcYvjdYY+lPIfz1UjssD+VrvAfKnbHLx0EUCZ0vQ4WOL+NWGfh+u52Y5Re6c3dgpwl1JBtmEa4NisvupNzesNoAZoO47DbL0FcGo0hBKCo2fntAJZ7JLcivtTeEzjImztZWd/OysGsWP+ajNuVI5cQ4MhrgyyFIyQ2TlJvH+RnsDxVjC5R8iSOOUOxnzmmUObvjqp2wS95GlGlnttwazncegADW/s6tQAV3KIsxdQGVrq5mceNG8XL5SxFU8pV/4eP8/BtoX/4QajGBDYhZ6sSg4lvR0MVm1tsd+i2PVl9W1g+nZmuUX5y+eWhp15XSh/eNARXFB4KI1LUihTZQRyxBqOkc6x3Zv9dbBG8b2uajOJxEjGdFfqX6PjTf3c8x+p0TJnPsz3Ca6lYhzmM9svFGy53HV1DFpmrbI59+W81aRlfEsQFOyvZBikfqJag+d8CaVTU6PKYpO9aYiqRu0HDcI8NhwB3RZZhJq4iMvRunvWVa3NN+24kVvl1ot+/EC29hM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/quidsup_notrack_trackers
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
